### ISSUE TITLE
网站code block显示异常？

### ISSUE THREAD

**Issue by roachsinai** [hikerpig/hikerpig.github.io#15]
![image](https://user-images.githubusercontent.com/9500049/88252557-3a893580-cce1-11ea-8788-1a2c3543b833.png)

http://hikerpig.github.io/2020/06/05/2020-06-05-Separate-Git-Config-By-Directories/

**Comment by hikerpig** [comment]
@roachsinai 是不是 highlight.js 加载失败了？
![image](https://user-images.githubusercontent.com/2259688/88264210-f9ebe500-ccfd-11ea-864a-f716d8e0ceed.png)

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/88265490-2c96dd00-cd00-11ea-8bb9-8587664f7edc.png)

是需要翻墙么？😃

**Comment by hikerpig** [comment]
好像是的... 因为我日常开 tizi ，实在是不知道... jsdelivr 都不行了么 😭。有空试一下 unpkg 行不行

**Comment by roachsinai** [comment]
好的!!!

**Comment by roachsinai** [comment]
好像可以了。

**Comment by hikerpig** [comment]
@roachsinai 😝 周末偷偷换了 unpkg ，被你发现了

**Comment by roachsinai** [comment]
😃
